version: '3.8'

services:

  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env